name: Code Safe

on:
  push:
    branches:
      - main  # Ajuste para os branches desejados
  pull_request:
    branches:
      - main  # Ajuste para os branches desejados

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest  # Corrigido de "lastes" para "latest"

      - name: Run Biome CI
        run: biome ci .

  secure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/jod'

      - name: Install dependencies
        run: npm install

      - name: Check dependencies with npm audit
        run: npm audit
